server {
    listen 80 default_server;
    server_name jed.so;
    root /usr/share/nginx/html;
    index index.html;
    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    server_name www.jed.so;
    return 301 https://jed.so$request_uri;
}
